package com.springboot.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "weather")
public class Weather implements Serializable{
	
	private static final long serialVersionUID =1L;
	
	private String rowId;
	private double temperature;
	
	@DynamoDBHashKey(attributeName ="rowId")
	@DynamoDBAutoGeneratedKey
	public String getRowId() {
		return rowId;
	}
	
	public void setRowId(String rowId)
	{
		this.rowId=rowId;
	}
	
	@DynamoDBRangeKey
	public double getTemperature() {
		return temperature;
	}
	
	public void setTemperature(double temperature)
	{
		this.temperature=temperature;
	}
}
